In [1]:
import numpy as np
from sklearn import preprocessing

In [2]:
data = np.array([[3, -1.5,  2, -5.4], 
                 [0,  4,  -0.3, 2.1], 
                 [1,  3.3, -1.9, -4.3]])

In [3]:
# Mean removal
data_standardized = preprocessing.scale(data) # defaults to scaling to a std normal
print "Mean          = ", data_standardized.mean(axis=0) # mean s/b 0
print "Std Deviation = ", data_standardized.std(axis=0)  # std dev s/b 1

Mean          =  [  5.55111512e-17  -1.11022302e-16  -7.40148683e-17  -7.40148683e-17]
Std Deviation =  [ 1.  1.  1.  1.]


In [5]:
# Scaling data
data_scaler = preprocessing.MinMaxScaler(feature_range=(0,1)) # scales features to (0,1)
data_scaled = data_scaler.fit_transform(data)
print "Min max scaled data = \n", data_scaled

Min max scaled data = 
[[ 1.          0.          1.          0.        ]
 [ 0.          1.          0.41025641  1.        ]
 [ 0.33333333  0.87272727  0.          0.14666667]]


In [6]:
# Normalized data
data_normalized = preprocessing.normalize(data, norm='l1')
print "L1 normalized data = \n", data_normalized

L1 normalized data = 
[[ 0.25210084 -0.12605042  0.16806723 -0.45378151]
 [ 0.          0.625      -0.046875    0.328125  ]
 [ 0.0952381   0.31428571 -0.18095238 -0.40952381]]


In [7]:
# Binarization
data_binarized = preprocessing.Binarizer(threshold=1.4).transform(data)
print "Binarized data = \n", data_binarized

Binarized data = 
[[ 1.  0.  1.  0.]
 [ 0.  1.  0.  1.]
 [ 0.  1.  0.  0.]]


In [11]:
# One Hot Encoding
encoder = preprocessing.OneHotEncoder()
encoder.fit([[0, 2, 1, 12],
             [1, 3, 5, 3 ],
             [2, 3, 2, 12],
             [1, 2, 4, 3 ]])
encoded_vector = encoder.transform([[2, 3, 5, 3]]).toarray()
print "Encoded vector = \n", encoded_vector

Encoded vector = 
[[ 0.  0.  1.  0.  1.  0.  0.  0.  1.  1.  0.]]


In [19]:
print "Categories = [[0, 1, 2]]   ", encoded_vector[:, 0:3]
print "Categories = [[2, 3]]      ", encoded_vector[:, 3:5]
print "Categories = [[1, 2, 4, 5]]", encoded_vector[:, 5:9]
print "Categories = [[3, 12]]     ", encoded_vector[:, 9:]

Categories = [[0, 1, 2]] [[ 0.  0.  1.]]
Categories = [[2, 3]] [[ 0.  1.]]
Categories = [[1, 2, 4, 5]] [[ 0.  0.  0.  1.]]
Categories = [[3, 12]] [[ 1.  0.]]


In [26]:
# Label encoding
label_encoder = preprocessing.LabelEncoder()
input_classes = ['audi', 'ford', 'audi', 'toyota', 'ford', 'bmw']
label_encoder.fit(input_classes)
print "Class Mapping"
for i, item in enumerate(label_encoder.classes_):
    print '  ', item, '-->', i

Class Mapping
   audi --> 0
   bmw --> 1
   ford --> 2
   toyota --> 3


In [27]:
labels = ['toyota', 'ford', 'audi']
encoded_labels = label_encoder.transform(labels)
print "Labels =        ", labels
print "Encoded labels =", list(encoded_labels)

Labels =         ['toyota', 'ford', 'audi']
Encoded labels = [3, 2, 0]


In [28]:
encoded_labels = [2,1,0,3,1]
decoded_labels = label_encoder.inverse_transform(encoded_labels)
print "Encoded labels =", encoded_labels
print "Decoded labels =", decoded_labels

Encoded labels = [2, 1, 0, 3, 1]
Decoded labels = ['ford' 'bmw' 'audi' 'toyota' 'bmw']
