In [1]:
import numpy as np

data = np.random.randn(2,3)

data

array([[ 1.13509817, -1.68588067,  0.19184868],
       [-0.15112397,  0.50617006, -1.2630878 ]])

In [2]:
data * 10

array([[ 11.35098166, -16.85880675,   1.91848682],
       [ -1.51123968,   5.06170058, -12.63087801]])

In [3]:
data + data

array([[ 2.27019633, -3.37176135,  0.38369736],
       [-0.30224794,  1.01234012, -2.5261756 ]])

In [5]:
print data.shape
print data.dtype

(2, 3)
float64


In [6]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)

arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [7]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [9]:
np.ones((10,2))

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [10]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [11]:
np.empty((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [12]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [14]:
np.full(12, 17.)

array([ 17.,  17.,  17.,  17.,  17.,  17.,  17.,  17.,  17.,  17.,  17.,
        17.])

In [15]:
my_data = np.arange(20)

In [16]:
my_data[5:8]

array([5, 6, 7])

In [17]:
my_data[2:11:2]

array([ 2,  4,  6,  8, 10])

In [18]:
my_data[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [19]:
my_data[::]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [21]:
my_data[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

In [23]:
my_shape = my_data.reshape((4,5))

my_shape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [24]:
my_shape.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [26]:
my_shape.mean(1)

array([  2.,   7.,  12.,  17.])