In [1]:
import numpy as np

data = np.random.randn(2,3)

data

array([[-0.10463149, -0.29989252,  1.02488325],
       [-0.64601018,  0.92761565, -0.84373363]])

In [2]:
data * 10

array([[ -1.04631492,  -2.99892523,  10.24883251],
       [ -6.46010184,   9.27615654,  -8.43733633]])

In [3]:
data + data

array([[-0.20926298, -0.59978505,  2.0497665 ],
       [-1.29202037,  1.85523131, -1.68746727]])

In [4]:
print data.shape
print data.dtype

(2, 3)
float64


In [5]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)

arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [6]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [7]:
np.ones((10,2))

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [8]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [9]:
np.empty((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [10]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [11]:
np.full(12, 17.)

array([ 17.,  17.,  17.,  17.,  17.,  17.,  17.,  17.,  17.,  17.,  17.,
        17.])

In [12]:
my_data = np.arange(20)

In [13]:
my_data[5:8]

array([5, 6, 7])

In [14]:
my_data[2:11:2]

array([ 2,  4,  6,  8, 10])

In [15]:
my_data[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [16]:
my_data[::]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [17]:
my_data[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

In [18]:
my_shape = my_data.reshape((4,5))

my_shape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [19]:
my_shape.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [20]:
my_shape.mean(1)

array([  2.,   7.,  12.,  17.])

In [25]:
np.random.seed(0)

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(3,4,5))

print "x3 ndim:", x3.ndim
print "x3 shape:", x3.shape
print "x3 size:", x3.size
print "x3 dtype:", x3.dtype
print "x3 itemsize", x3.itemsize, "bytes"
print "x3 nbytes", x3.nbytes, "bytes" # nbytes = itemsize * size

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60
x3 dtype: int64
x3 itemsize 8 bytes
x3 nbytes 480 bytes


In [26]:
x1

array([5, 0, 3, 3, 7, 9])

In [27]:
x1[0]

5

In [28]:
x1[4]

7

In [29]:
x1[-1]

9

In [30]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [31]:
x2[0,0]

3

In [32]:
x2[2,0]

1

In [33]:
x2[2,-1]

7

In [34]:
x2[0,0]=12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [35]:
x1[0] = 3.14159
x1

array([3, 0, 3, 3, 7, 9])

Slicing arrays looks like x[start = 0:stop = size :step = 1]

In [36]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
x[:5] # first five

array([0, 1, 2, 3, 4])

In [38]:
x[5:] # elements after 5

array([5, 6, 7, 8, 9])

In [39]:
x[4:7]

array([4, 5, 6])

In [40]:
x[::2] # every other element

array([0, 2, 4, 6, 8])

In [41]:
x[1::2] # now starting at 1

array([1, 3, 5, 7, 9])

In [42]:
x[::-1] # reverse it

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [43]:
x[5::-2] # reversed, starting at 5 every other one

array([5, 3, 1])

In [44]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [45]:
x2[:2,:3] #first two rows, first three cols

array([[12,  5,  2],
       [ 7,  6,  8]])

In [46]:
x2[:3, ::2] # all rows, every other column

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [47]:
x2[::-1,::-1] # reverse the rows and columns

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [49]:
print x2[:, 0] # first column
print x2[0, :] # first row
print x2[0] # also first row

[12  7  1]
[12  5  2  4]
[12  5  2  4]


In [51]:
print x2

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [52]:
x2_sub = x2[:2,:2]
print x2_sub

[[12  5]
 [ 7  6]]


In [53]:
x2_sub[0,0] = 99  # mess with a slice - beware!, you are only dealing with a view - not a copy

print x2

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [54]:
x2_sub_copy = x2[:2, :2].copy()

print x2_sub_copy

[[99  5]
 [ 7  6]]


In [55]:
x2_sub_copy[0,0] = 42

print x2_sub_copy
print ''
print x2 # see, it's still 99, not 42

[[42  5]
 [ 7  6]]

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


** Reshaping of arrays **

In [57]:
grid = np.arange(1,10).reshape((3,3))

print grid

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [58]:
x = np.array([1,2,3])

x.reshape((1,3))

array([[1, 2, 3]])

In [59]:
x[np.newaxis, :] # same thing as the prior reshape

array([[1, 2, 3]])

In [60]:
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [61]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

**Array Concatenation**